import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import variables from "./variables.module.scss";
import "./globals.scss";

const fontSans = Inter_Tight({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background: variables.white,
        }}
        className={`${fontSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
